// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwjpgsbwqtghyuoeasje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3anBnc2J3cXRnaHl1b2Vhc2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mzc1MTcsImV4cCI6MjA2NDMxMzUxN30.0kazVgRZI5l9RCbb6F_zs5Ns-qjS3nSs907YGxhFm-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);